name: Proselint Markdown Files

on:
  push:
    paths:
      - '*/.md'

jobs:
  proselint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Proselint
        run: sudo apt-get update && sudo apt-get install proselint -y

      - name: Run Proselint
        run: proselint */.md
