name: ShellCheck

on:
  push:
    paths:
      - '*/.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install shellcheck -y

      - name: Run ShellCheck
        run: shellcheck */.sh


